<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="net"
    nsURI="http://www.net" nsPrefix="net">
  <eSubpackages name="java" nsURI="http://www.java.net" nsPrefix="java">
    <eSubpackages name="treaty" nsURI="http://java.treaty.net" nsPrefix="treaty">
      <eSubpackages name="eclipse" nsURI="http://java.treaty.net/eclipse" nsPrefix="eclipse">
        <eSubpackages name="vocabulary" nsURI="http://java.treaty.net/eclipse/vocabulary"
            nsPrefix="vocabulary">
          <eSubpackages name="ocl" nsURI="http://java.treaty.net/eclipse/vocabulary/ocl"
              nsPrefix="ocl">
            <eSubpackages name="test" nsURI="http://java.treaty.net/eclipse/vocabulary/ocl/test"
                nsPrefix="test">
              <eSubpackages name="base">
                <eSubpackages name="model" nsURI="http://java.treaty.net/eclipse/vocabulary/ocl/test/model"
                    nsPrefix="model">
                  <eClassifiers xsi:type="ecore:EClass" name="TestInterface">
                    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
                    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
                    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName"
                        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
                  </eClassifiers>
                </eSubpackages>
              </eSubpackages>
            </eSubpackages>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
